### ISSUE TITLE
Error when executing the migrate command

### ISSUE THREAD

**Issue by Navaneethp360** [DAKSHSEMWAL/Music-Genre-Classification#1]
C:\Users\navan\Downloads\Music-Genre-Classification-master>python manage.py migrate
Traceback (most recent call last):
  File "C:\Users\navan\Downloads\Music-Genre-Classification-master\manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\commands\migrate.py", line 91, in handle
    self.check(databases=[database])
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 487, in check
    all_issues = checks.run_checks(
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\navan\Downloads\Music-Genre-Classification-master\django-jquery-file-upload\urls.py", line 2, in <module>
    from django.conf.urls import include, url
ImportError: cannot import name 'url' from 'django.conf.urls' (C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\conf\urls\__init__.py)

Please help me how to resolve it and run the code

**Comment by Hima-nshu** [comment]
> C:\Users\navan\Downloads\Music-Genre-Classification-master>python manage.py migrate Traceback (most recent call last): File "C:\Users\navan\Downloads\Music-Genre-Classification-master\manage.py", line 25, in execute_from_command_line(sys.argv) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management__init__.py", line 446, in execute_from_command_line utility.execute() File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management__init__.py", line 440, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 414, in run_from_argv self.execute(*args, **cmd_options) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 460, in execute output = self.handle(*args, **options) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 98, in wrapped res = handle_func(*args, **kwargs) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\commands\migrate.py", line 91, in handle self.check(databases=[database]) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\base.py", line 487, in check all_issues = checks.run_checks( File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks new_errors = check(app_configs=app_configs, databases=databases) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique all_namespaces = _load_all_namespaces(resolver) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces url_patterns = getattr(resolver, "url_patterns", []) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 49, in **get** res = instance.**dict**[self.name] = self.func(instance) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 696, in url_patterns patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 49, in **get** res = instance.**dict**[self.name] = self.func(instance) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 689, in urlconf_module return import_module(self.urlconf_name) File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\navan\Downloads\Music-Genre-Classification-master\django-jquery-file-upload\urls.py", line 2, in from django.conf.urls import include, url ImportError: cannot import name 'url' from 'django.conf.urls' (C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\django\conf\urls__init__.py)
> 
> Please help me how to resolve it and run the code

please help how to resolve the error
